;;; test-helmholtz-kohlrausch.el --- Helmholtz-Kohlrausch chromatic brightness boost -*- lexical-binding: t; -*-

(require 'test-palette-extractor)

(defun test-helmholtz-kohlrausch-run ()
  "Evaluate Helmholtz-Kohlrausch (H-K) perceived brightness per Fairchild & Pirrotta (1991)."
  (let* ((pal (rainforest-extract-active-palette))
         (theme (plist-get pal :theme))
         (passes 0)
         (warnings 0)
         (tokens '(("Base text (Mineral quartz)"       :fg-main)
                   ("Comments (Damp needles)"          :fg-dim)
                   ("Cursor (Raindrop glint)"          :cursor)
                   ("Preprocessor (#define)"           :preprocessor)
                   ("Keywords (struct, while)"         :keyword)
                   ("Data types (int, size_t)"         :type)
                   ("Constants (LOTA_PCR_COUNT)"       :constant)
                   ("Numbers (0, 24, 32)"              :number)
                   ("Builtins (__always_inline)"       :builtin)
                   ("Function definitions"             :fnname)
                   ("Function calls (bpf_...)"         :fnname-call)
                   ("Strings (\"string literals\")"    :string)
                   ("Struct fields (->tgid)"           :property)
                   ("Operators (+, -, *, >>)"          :operator)
                   ("Brackets (( ) [ ] { })"           :bracket)
                   ("Alerts / Errors (!)"              :err))))
    (princ (format "\n======================================================================\n"))
    (princ (format " Helmholtz-Kohlrausch (H-K) Chromatic Brightness Enhancement Suite\n"))
    (princ (format " Ref: Fairchild & Pirrotta (1991), Nayatani (1997) Color Res. Appl.\n"))
    (princ (format " Theme: %s\n" theme))
    (princ (format "======================================================================\n"))
    (princ (format "%-32s | %-8s | %-8s | %-6s | %-9s | %-10s\n"
                   "Token Role" "Hex" "Phot Y" "C*" "H-K Boost" "Perceived B"))
    (princ (format "---------------------------------+----------+----------+--------+-----------+-----------\n"))
    (dolist (tok tokens)
      (let* ((name (nth 0 tok))
             (key  (nth 1 tok))
             (hex (plist-get pal key))
             (y   (rf-luminance-y hex))
             (c   (rf-cielab-chroma hex))
             (hk-factor (rf-helmholtz-kohlrausch-factor hex))
             (perceived (* y hk-factor)))
        (setq passes (1+ passes))
        (princ (format "%-32s | %-8s | %8.4f | %6.1f | +%5.1f%%    | %8.4f\n"
                       name hex y c (* (- hk-factor 1.0) 100.0) perceived))))
    (princ (format "---------------------------------+----------+----------+--------+-----------+-----------\n"))
    (princ "Biophysical Principle:\n")
    (princ "Highly saturated colors (high C*) stimulate human perceived brightness\n")
    (princ "through L-M and S-(L+M) opponent channels without requiring gamma elevation.\n")
    (princ "This proves: To make colors brighter without washed-out gray haze, preserve Chroma!\n")
    (princ (format "----------------------------------------------------------------------\n"))
    (princ (format "Helmholtz-Kohlrausch Summary: %d Evaluated.\n\n" passes))
    t))

(when (and noninteractive (not (bound-and-true-p rf-running-all-tests)))
  (unless (test-helmholtz-kohlrausch-run)
    (kill-emacs 1)))

(provide 'test-helmholtz-kohlrausch)
;;; test-helmholtz-kohlrausch.el ends here
