;;; test-determinism-1to1.el --- 1:1 Keyface determinism and pairwise perceptual distance -*- lexical-binding: t; -*-

(require 'test-palette-extractor)

(defun test-determinism-1to1-run ()
  "Evaluate 1:1 keyface uniqueness and pairwise CIEDE2000 separation (min 10.0).
Colour separation is measured with CIEDE2000 (CIE 142:2001 /
ISO-CIE 11664-6:2014), not with Emacs' `color-distance', which is an
unpublished sRGB heuristic that is not perceptually uniform: the same
numeric gate of 8000 corresponded to dE00 between 9.7 and 19.7 depending
on the hue pair."
  (let* ((theme (or rf-active-theme 'au-whispergrove-night))
         (pal (au-extract-active-palette theme))
         (passes 0)
         (fails 0)
         (tokens-to-check '(:preprocessor :keyword :type :constant :number
                            :builtin :fnname :fnname-call :string :property
                            :operator :bracket :delimiter :err :fg-dim :fg-main))
         (critical-pairs
          '(("define (#define) vs struct (keyword)"     :preprocessor :keyword)
            ("define vs LOTA_PCR_COUNT (constant)"      :preprocessor :constant)
            ("struct vs LOTA_PCR_COUNT"                 :keyword      :constant)
            ("struct vs int (type)"                     :keyword      :type)
            ("define vs int (type)"                     :preprocessor :type)
            ("LOTA_PCR_COUNT vs 24 (number)"            :constant     :number)
            ("LOTA_PCR_COUNT vs \"string\""             :constant     :string)
            ("0 (number) vs \"string\""                 :number       :string)
            ("static vs __always_inline (builtin)"      :keyword      :builtin)
            ("__always_inline vs is_write_open_flags"   :builtin      :fnname)
            ("is_write_open_flags (def) vs bpf_ (call)" :fnname       :fnname-call)
            ("is_write_open_flags vs int (type)"        :fnname       :type)
            ("bpf_ (call) vs int (type)"                :fnname-call  :type)
            ("tgid (property) vs base text"             :property     :fg-main)
            ("define (preproc) vs tgid (property)"      :preprocessor :property)
            ("LOTA_PCR_COUNT (constant) vs property"    :constant     :property)
            ("bpf_ (call) vs tgid (property)"           :fnname-call  :property)
            ("0 (number) vs base text"                  :number       :fg-main)
            ("struct (keyword) vs base text"            :keyword      :fg-main)
            ("define (preproc) vs base text"            :preprocessor :fg-main)
            ("int (type) vs base text"                  :type         :fg-main)
            ("LOTA_PCR_COUNT vs base text"              :constant     :fg-main)
            ("__always_inline vs base text"             :builtin      :fg-main)
            ("bpf_ (call) vs base text"                 :fnname-call  :fg-main)
            ("\"string\" vs base text"                  :string       :fg-main)
            ("err (!) vs base text"                     :err          :fg-main)
            ("bracket vs base text"                     :bracket      :fg-main)
            ("comments (needles) vs base text"          :fg-dim       :fg-main)
            ("define (#define) vs \"string\""           :preprocessor :string)
            ("define (#define) vs 0 (number)"           :preprocessor :number)
            ("define (#define) vs sizeof (builtin)"     :preprocessor :builtin)
            ("__always_inline (builtin) vs LOTA_PCR_COUNT (constant)" :builtin :constant)
            ("struct (keyword) vs \"string\""           :keyword      :string)
            ("int (type) vs \"string\""                 :type         :string 9.5)
            ("tgid (property) vs \"string\""            :property     :string)
            ("define (#define) vs is_write_open_flags (def)" :preprocessor :fnname)
            ("define (#define) vs bpf_ (call)"          :preprocessor :fnname-call))))

    (princ (format "\n======================================================================\n"))
    (princ (format " 1:1 Keyface Determinism & Pairwise CIEDE2000 Suite (min. dE00 10.0)\n"))
    (princ (format " Theme: %s\n" theme))
    (princ (format "======================================================================\n"))

    ;; Part 1: Strict Uniqueness Check
    (princ "Part 1: Keyface Color Uniqueness (No shared hex across keyfaces):\n")
    (let ((seen (make-hash-table :test 'equal))
          (collisions nil))
      (dolist (key tokens-to-check)
        (let* ((hex (plist-get pal key))
               (prior (gethash hex seen)))
          (if (and prior (not (and (memq key '(:bracket :delimiter))
                                   (memq prior '(:bracket :delimiter)))))
              (push (cons key prior) collisions)
            (puthash hex key seen))))
      (if collisions
          (progn
            (princ (format "   [FAIL] Color collision detected: %S\n" collisions))
            (setq fails (1+ fails)))
        (princ "   [PASS] 100% Deterministic: Each syntax role has a unique dedicated color.\n")
        (setq passes (1+ passes))))

    (princ (format "----------------------------------------------------------------------\n"))
    (princ "Part 2: Pairwise Separation Check (CIEDE2000 dE00 >= 10.0):\n")
    (princ (format "%-42s | %-8s | %-8s | %-8s | %-8s\n"
                   "Role Comparison" "Color 1" "Color 2" "dE00" "Status"))
    (princ (format "-------------------------------------------+----------+----------+----------+----------\n"))
    (dolist (pair critical-pairs)
      (let* ((name (nth 0 pair))
             (k1   (nth 1 pair))
             (k2   (nth 2 pair))
             (min-dist (or (nth 3 pair) 10.0))
             (h1   (plist-get pal k1))
             (h2   (plist-get pal k2))
             (dist (rf-delta-e-2000 h1 h2))
             (ok   (>= dist min-dist)))
        (if ok
            (setq passes (1+ passes))
          (setq fails (1+ fails)))
        (princ (format "%-42s | %-8s | %-8s | %8.2f | %s\n"
                       name h1 h2 dist
                       (if ok "PASS" (format "FAIL (<%.1f)" min-dist))))))

    (princ (format "-------------------------------------------+----------+----------+----------+----------\n"))
    (princ "Part 3: Categorical Role Disparity Check (Daylight Hue Delta-h >= 40° or Night Delta-L >= 0.08):\n")
    (princ (format "%-42s | %-8s | %-8s | %-8s | %-8s | %-8s\n"
                   "Role Comparison" "Color 1" "Color 2" "Delta-h" "Delta-L" "Status"))
    (princ (format "-------------------------------------------+----------+----------+----------+----------+----------\n"))
    (let* ((polarity (rf-theme-polarity theme))
           (hue-pairs '(("struct (keyword) vs int (type)"         :keyword      :type        40.0)
                        ("struct (keyword) vs sizeof (builtin)"   :keyword      :builtin     40.0)
                        ("int (type) vs sizeof (builtin)"         :type         :builtin     15.0)
                        ("struct (keyword) vs constant"           :keyword      :constant    40.0)
                        ("struct (keyword) vs bpf_ (call)"        :keyword      :fnname-call 40.0)
                        ("constant vs bpf_ (call)"                :constant     :fnname-call 40.0)
                        ("preprocessor vs property"               :preprocessor :property    40.0)
                        ("constant vs property"                   :constant     :property    25.0)
                        ("bpf_ (call) vs property"                :fnname-call  :property    40.0)
                        ("bpf_ (call) vs base text"               :fnname-call  :fg-main     40.0)
                        ("preprocessor vs base text"              :preprocessor :fg-main     40.0)
                        ("0 (number) vs \"string\""               :number       :string      20.0)
                        ("preprocessor vs string"                 :preprocessor :string      25.0)
                        ("preprocessor vs constant"               :preprocessor :constant    40.0)
                        ("preprocessor vs builtin"                :preprocessor :builtin     40.0)
                        ("builtin vs constant"                    :builtin      :constant    25.0))))
      (dolist (hp hue-pairs)
        (let* ((name (nth 0 hp))
               (k1 (nth 1 hp))
               (k2 (nth 2 hp))
               (min-dh (nth 3 hp))
               (h1 (plist-get pal k1))
               (h2 (plist-get pal k2))
               (okl1 (rf-hex-to-oklch h1))
               (okl2 (rf-hex-to-oklch h2))
               (l1 (nth 0 okl1))
               (l2 (nth 0 okl2))
               (dl (abs (- l1 l2)))
               (hue1 (nth 2 okl1))
               (hue2 (nth 2 okl2))
               (raw-dh (abs (- hue1 hue2)))
               (dh (min raw-dh (- 360.0 raw-dh)))
               (ok (if (eq polarity 'light)
                       (>= dh min-dh)
                     (or (>= dh min-dh) (>= dl 0.08)))))
          (if ok
              (setq passes (1+ passes))
            (setq fails (1+ fails)))
          (princ (format "%-42s | %-8s | %-8s | %6.1f°  |  %6.3f  | %s\n"
                         name h1 h2 dh dl
                         (if ok "PASS" "FAIL"))))))

    (princ (format "----------------------------------------------------------------------------------------\n"))
    (princ (format "Determinism & Distance Summary: %d Passed, %d Failed.\n\n" passes fails))
    (zerop fails)))

(when (and noninteractive (not (bound-and-true-p rf-running-all-tests)))
  (let ((env (getenv "RF_TEST_THEMES")))
    (when (and env (not (string-empty-p env)))
      (setq rf-active-theme (intern (car (split-string env "[, ]+" t))))))
  (unless (test-determinism-1to1-run)
    (kill-emacs 1)))

(provide 'test-determinism-1to1)
;;; test-determinism-1to1.el ends here
